---
ALLOWED_HOSTS:
- 127.0.0.1
- localhost
DEBUG: true

ENVIRONMENT: 'localhost'
# ENVIRONMENT: 'production'

# TODO: CLEAN UP

# To pretend we are a reviewapp, set these two:
# ENVIRONMENT: 'reviewapp'
# PRIVATE_S3_BUCKET_PREFIX: 'pr249/'

LOG_LEVEL: DEBUG
DATABASE_URL: postgres://localhost:5432/poynter
SECRET_KEY: uJ8dIF2VP7s67yhnsK&ddasCoASTGlB9cO4f8gxt7L2k7RI5XLs9IJhF$skOnbV4WJUSFSWJFDvEhVD267H

# Use "background" for qcluster, foreground for debugging
# ASYNC_DEFAULT: "foreground"
ASYNC_DEFAULT: "background"





# LOCAL DEV transferring data from Iris to cosmos, set these temporarily
# to the cosmos server bucket/prefix you're pushing to. Not normally needed.
# PRIVATE_S3_BUCKET_NAME: "apppack-app-cosmos-prod-privates3bucket-clugo9ev2l79"
# PRIVATE_S3_BUCKET_PREFIX: "cosmos-prod/"

# OPENSEARCH_INDEX_RETENTION: 3

# PRIVATE_S3_BUCKET_PREFIX: "pr220/"
